pipeline {
    agent any
    environment {
        PROJECT_ID = 'bubbly-display-313214'
        CLUSTER_NAME = 'k8s-dev'
        LOCATION = 'us-central1-a'
        stage("Checkout code") {
            steps {
                checkout scm
            }
        }       
        stage('Deploy to GKE') {
            steps{
                step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'deployment.yaml', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
            }
        }
    }    
}
